export enum TAB_BAR_NAVIGATOR_ROUTES {
  ACCOUNT = 'ACCOUNT',
  CARROT = 'CARROT',
  SEARCH = 'SEARCH',
  QRSCAN = 'QRSCAN',
  PLATE = 'PLATE',
}

export type TabBarNavigatorParamList = {
  [TAB_BAR_NAVIGATOR_ROUTES.ACCOUNT]: undefined;
  [TAB_BAR_NAVIGATOR_ROUTES.CARROT]: undefined;
  [TAB_BAR_NAVIGATOR_ROUTES.SEARCH]: undefined;
  [TAB_BAR_NAVIGATOR_ROUTES.QRSCAN]: undefined;
  [TAB_BAR_NAVIGATOR_ROUTES.PLATE]: undefined;
};
